server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/diarydb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
        #    properties:
        #      hibernate:
      # show_sql: true
  #        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: itsdiaryservice@gmail.com
    password: rvbaoetaqfbwtghn
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  h2:
    console:
      enabled: true

#  redis:
#    host: localhost
#    port: 6379

#logging.level:
#  org.hibernate.SQL: debug
# org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: YSOSeNbBPqDe1KYSDoNLy18DRCHalQ3ev+IpDOsMUDU=

github:
  client:
    id: 189505605f083d3c6449
    secret: 42125c8c0e29a55f46bff3abb3f74def876705ab
  url:
    access-token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user

#Authorization url :
#  https://accounts.google.com/o/oauth2/v2/auth?scope=https://www.googleapis.com/auth/userinfo.profile&redirect_uri=http://localhost:3000/login/oauth2/callback&response_type=code&client_id=225651924488-oq3i2bo15p16qvnmad43hpabphts956u.apps.googleusercontent.com
google:
  client:
    id: 225651924488-oq3i2bo15p16qvnmad43hpabphts956u.apps.googleusercontent.com
    secret: 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
  redirect-uri: http://localhost:3000/login/oauth2/callback
  grant-type: authorization_code
  url:
    access-token: https://oauth2.googleapis.com/token
    profile: https://www.googleapis.com/oauth2/v2/userinfo

#Authorization url:
#https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=c7893734cf9af631da8451f73fe618b8&redirect_uri=http://localhost:3000/login/oauth2/callback
kakao:
  client:
    id: c7893734cf9af631da8451f73fe618b8
    secret: 8S8JTnTu9PChRr74K0I1IxLtjzqTk59o
  redirect-uri: http://localhost:3000/login/oauth2/callback
  grant-type: authorization_code
  url:
    access-token: https://kauth.kakao.com/oauth/token
    profile: https://kapi.kakao.com/v2/user/me

springdoc:
  swagger-ui:
    # swagger-ui 접근 경로
    path: /swagger-custom-ui.html