### 일기방 생성 및 초대
POST http://localhost:8080/api/v0/diary-rooms
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjk0OTI5NzE5LCJleHAiOjE2OTQ5MzE1MTl9.P08PYJoyjgMyqwG4msgYE8yK_WeTwAhUt0FRGBkXTZ4
Content-Type: application/json

{
  "name" : "Today Diary",
  "emails" : [
    "gch03915@naver.com",
    "unionfind@kakao.com"
  ]
}